# -*- coding: utf-8 -*-
"""Untitled47.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J9R1R43uH3qMjGhXrQ9_DO8jShAC4eL8
"""

from flask import Flask, request, jsonify
from sentence_transformers import SentenceTransformer
import os

app = Flask(__name__)

# Load the Sentence Transformer model
model_path = os.getenv('MODEL_PATH', './sentence_t5_base_model')  # Default path to model
model = SentenceTransformer(model_path)

@app.route('/embed', methods=['POST'])
def embed():
    data = request.get_json()
    text = data.get('text')
    if text:
        # Generate embeddings
        embedding = model.encode(text, convert_to_tensor=False).tolist()  # Convert numpy array to list for JSON serialization
        return jsonify({'embedding': embedding})
    else:
        return jsonify({'error': 'No text provided'}), 400

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=int(os.getenv('PORT', 8080)))  # Default port 8080